### ISSUE TITLE
Typo found in README.md

### ISSUE THREAD

**Issue by daesavellano** [allegheny-college-cmpsc-200-fall-2023/course-materials#1]
⚠️ **The heading in README.md has an error!** It says "CMPSC 100" instead of "CMPSC 200" (see image and link below).

🔗 Link: https://github.com/allegheny-college-cmpsc-200-fall-2023/course-materials#cmpsc-100-computer-organization

![image](https://github.com/allegheny-college-cmpsc-200-fall-2023/course-materials/assets/20417724/6ad32cec-53db-4766-abcf-5e6ac93bf4e8)

The fix for this issue is simple: Change it to "CMPSC 200" for accuracy.

Help us spread the word about the correction to "CMPSC 200"! Unlock the potential of accurate information! Thank you for your attention! 🙏

**Comment by dluman** [comment]
Addressed in latest commit. Thanks!
